project:
  type: website

website:
  title: "Votre Titre"
  navbar:
    left:
      - text: "Home"
        href: /_site/index.html
    right:
      - icon: github
        href: https://github.com/WolfPackStatMathieu/tuto_quarto_article.git

format:
  html:
    toc: true
    number-sections: true
